name: NPM Release

on:
  workflow_call:
    inputs:
      version:
        description: "Release Version"
        required: true
        type: string
      publishTag:
        description: "Tag under which to release the packages (defaults to latest)"
        required: false
        default: "latest"
        type: string
      dryRun:
        description: "true if dry run release, false otherwise"
        required: false
        default: false
        type: boolean

jobs:
  npm_release:
    name: NPM Release Matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          [
            "wasm",
            "functions-runtime",
            "testing-runtime",
            "client-react",
            "client-react-query",
          ]
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: "1.20"

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2.4.0
        with:
          version: 8.5.1

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0

      - name: Install Go deps
        if: inputs.publishTag != 'latest'
        run: go mod download

      - name: Generate wasm binary
        if: ${{ matrix.package  == 'wasm' && inputs.publishTag != 'latest' }}
        run: make wasm

      - name: Install ${{ matrix.package }} publish dependencies
        working-directory: ./packages/${{ matrix.package }}
        run: pnpm install --frozen-lockfile

      - name: "Update NPM version ${{ matrix.package }}"
        if: inputs.publishTag != 'latest'
        uses: reedyuk/npm-version@1.2.1
        with:
          version: ${{ inputs.version }}
          package: ./packages/${{ matrix.package }}

      - name: NPM Publish ${{ matrix.package }}
        uses: JS-DevTools/npm-publish@v2
        with:
          token: ${{ secrets.NPM_TOKEN }}
          tag: ${{ inputs.publishTag }}
          package: ./packages/${{ matrix.package }}
          dry-run: ${{ inputs.dryRun }}
          strategy: all
          ignore-scripts: false
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    outputs:
      version: ${{ inputs.version }}
