name: Prepare Keel Release

on:
  workflow_dispatch:
    inputs:
      backendBranch:
        description: "The backend branch that triggered this release"
        required: true
        type: string
      preReleaseVersion:
        description: "Pre Release Version to release"
        required: true
        type: string
      releaseNotesUrl:
        description: "URL to release notes for version"
        required: false
        type: string
      sendUpdateEvent:
        description: Raise PR against backend
        required: false
        type: boolean
        default: true
  workflow_call:
    inputs:
      backendBranch:
        description: "The backend branch that triggered this release"
        required: true
        type: string
      preReleaseVersion:
        description: "Pre Release Version to release"
        required: true
        type: string
      releaseNotesUrl:
        description: "URL to release notes for version"
        required: false
        type: string
      sendUpdateEvent:
        description: Raise PR against backend
        required: false
        type: boolean
        default: true

jobs:
  create_branch:
    name: Create release branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: teamkeel/keel
          ref: "v${{ inputs.preReleaseVersion }}"
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0

      # generate a new version number based on semantic versioning
      - name: Generate version
        id: generate-version
        uses: paulhatch/semantic-version@v5.0.3
        with:
          tag_prefix: "v"
          major_pattern: "^([A-Za-z]+.)*!:.*$"
          major_regexp_flags: "g"
          minor_pattern: "feat"
          version_format: "${major}.${minor}.${patch}"

      - name: Create new release branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: "refs/heads/release/v${{ steps.generate-version.outputs.version }}"
          sha: ${{ github.sha }}

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: teamkeel/keel
          ref: release/v${{ steps.generate-version.outputs.version }}
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0
    outputs:
      version: ${{ steps.generate-version.outputs.version }}

  npm_release:
    uses: ./.github/workflows/npm_release.yml
    needs: [create_branch]
    with:
      version: ${{ needs.create_branch.outputs.version }}
      publishTag: rc-next
      dryRun: false
    secrets: inherit

  github_release:
    needs: [create_branch, npm_release]
    uses: ./.github/workflows/github_release.yml
    with:
      version: ${{ needs.create_branch.outputs.version }}
      preRelease: false
      draft: true
      makeLatest: false
      generateChangelog: false
      branch: "release/v${{ needs.create_branch.outputs.version }}"
      releaseNotesURL: ${{ inputs.releaseNotesUrl }}
      eventBranch: ${{ inputs.backendBranch }}
      publishEvent: ${{ inputs.sendUpdateEvent }}
    secrets: inherit
