name: Publish Keel Release

on:
  workflow_call:
    inputs:
      version:
        description: "Release Version"
        required: true
        type: string

jobs:
  npm_release:
    uses: ./.github/workflows/npm_release.yml
    with:
      version: ${{ inputs.version }}
      publishTag: latest
      dryRun: false
    secrets: inherit

  github_release:
    name: Make Github Release
    runs-on: ubuntu-latest
    needs: [npm_release]
    steps:
      - name: Publish Release
        id: publish_release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: "v${{ inputs.version }}"
          commit: "release/v${{ inputs.version }}"
          draft: false
          makeLatest: true
          prerelease: false
          allowUpdates: true
          updateOnlyUnreleased: true
